### ISSUE TITLE
Clarification: Core Docs

### ISSUE THREAD

**Issue by okhaimie-dev** [aragon/developer-portal#124]
On this page
[The Smart Contracts behind DAOs](https://devs.aragon.org/docs/osx/how-it-works/core/plugins/)

I would like to clarify if this section should be moved from `01-core` section to a new section `03-plugins`?. It seems to be an explanation of how plugins work which is out of the scope aragon `core` section that is being explained there. The Plugins contracts in Aragon `core` are base contract for building plugins.

Also I was thinking of making a separate section for Plugins.
![CleanShot 2023-08-07 at 19 16 54](https://github.com/aragon/developer-portal/assets/57156589/29a09388-61a1-41a7-bb18-78593977f8ec)

**Comment by novaknole** [comment]
We have been restructuring the documentation and hopefully, will be live soon.

Closing this issue as it's no longer relevant.
